		
		

var levDist = function(s, t) {
    var d = []; //2d matrix

    // Step 1
    var n = s.length;
    var m = t.length;

    if (n == 0) return m;
    if (m == 0) return n;

    //Create an array of arrays in javascript (a descending loop is quicker)
    for (var i = n; i >= 0; i--) d[i] = [];

    // Step 2
    for (var i = n; i >= 0; i--) d[i][0] = i;
    for (var j = m; j >= 0; j--) d[0][j] = j;

    // Step 3
    for (var i = 1; i <= n; i++) {
        var s_i = s.charAt(i - 1);

        // Step 4
        for (var j = 1; j <= m; j++) {

            //Check the jagged ld total so far
            if (i == j && d[i][j] > 4) return n;

            var t_j = t.charAt(j - 1);
            var cost = (s_i == t_j) ? 0 : 1; // Step 5

            //Calculate the minimum
            var mi = d[i - 1][j] + 1;
            var b = d[i][j - 1] + 1;
            var c = d[i - 1][j - 1] + cost;

            if (b < mi) mi = b;
            if (c < mi) mi = c;

            d[i][j] = mi; // Step 6

            //Damerau transposition
            if (i > 1 && j > 1 && s_i == t.charAt(j - 2) && s.charAt(i - 2) == t_j) {
                d[i][j] = Math.min(d[i][j], d[i - 2][j - 2] + cost);
            }
        }
    }

    // Step 7
    return d[n][m];
}

function compareAsc(a,b) {
  if (a.score < b.score)
     return -1;
  if (a.score > b.score)
    return 1;
  return 0;
}


function compareDesc(a,b) {
  if (a.score < b.score)
     return 1;
  if (a.score > b.score)
    return -1;
  return 0;
}

var strStartsWith = function(str, prefix) {
    return str.toLowerCase().indexOf(prefix.toLowerCase()) === 0;
}

var Search = function(
    searchWord,
    phraseDicList,
    fuzzyness)
{
	//this will hold all of the phrases, and their scores
    var foundWords = [];

    $.each(phraseDicList, function(i,s)
    {
		var id = s.id;
		var words = s.value;
	
        // Calculate the Levenshtein-distance:
		
		//levenshteinDistances will hold the array of words and their scores 
		var levenshteinDistances = [];
		
		//
		//phrase may contain multiple words
		//
		// don't go this route if user types in spaces
		//if(searchWord.split(" ").length<=1){
			$.each(words.split(" "), function(i,w){
				var levenshteinDistance = levDist(searchWord, w);
				// Length of the longer string:
				var length = Math.max(searchWord.length, w.length);
				// Calculate the score:
				var score = 1.0 - (levenshteinDistance / length);
				
				//if we are matching the string prefix, overwrite score
				if(strStartsWith(w,searchWord)){
					score =1.0 - (1/(searchWord.length/w.length))/100;
				}
				
				var levenshteinDistanceObj = {id:id, score: score, words:words, winner:w};
				levenshteinDistances.push(levenshteinDistanceObj);
			});
		//}
		
		//
		//treat the phrase as a single word
		//
		var levenshteinDistance = levDist(searchWord, words);
		// Length of the longer string:
		var length = Math.max(searchWord.length, words.length);
		// Calculate the score:
		var score = 1.0 - (levenshteinDistance / length);
		var levenshteinDistanceObj = {id:id, score: score, words:words};
		levenshteinDistances.push(levenshteinDistanceObj);
				
				
		//of all the possible scores, pick the highest to represent this phrase
		var sList = levenshteinDistances.sort(compareDesc);
		
		//only pick the top most score, which will represent the phrase
		var topMatch = sList[0];
		
		//limit results
        if (topMatch.score >= fuzzyness){
			foundWords.push(topMatch);
		}
		
    });
	
	//sort results, most relevant at top
	var sortable = foundWords.sort(compareDesc);

    return foundWords;
}



	var word = "pojo";
    var phraseList = [
{id:111110, value: "Soybean Farming"},
{id:111120, value: "Oilseed (except Soybean) Farming"},
{id:111130, value: "Dry Pea and Bean Farming"},
{id:111140, value: "Wheat Farming"},
{id:111150, value: "Corn Farming"},
{id:111160, value: "Rice Farming"},
{id:111191, value: "Oilseed and Grain Combination Farming"},
{id:111199, value: "All Other Grain Farming"},
{id:111211, value: "Potato Farming"},
{id:111219, value: "Other Vegetable (except Potato) and Melon Farming"},
{id:111310, value: "Orange Groves"},
{id:111320, value: "Citrus (except Orange) Groves"},
{id:111331, value: "Apple Orchards"},
{id:111332, value: "Grape Vineyards"},
{id:111333, value: "Strawberry Farming"},
{id:111334, value: "Berry (except Strawberry) Farming"},
{id:111335, value: "Tree Nut Farming"},
{id:111336, value: "Fruit and Tree Nut Combination Farming"},
{id:111339, value: "Other Noncitrus Fruit Farming"},
{id:111411, value: "Mushroom Production"},
{id:111419, value: "Other Food Crops Grown Under Cover"},
{id:111421, value: "Nursery and Tree Production"},
{id:111422, value: "Floriculture Production"},
{id:111910, value: "Tobacco Farming"},
{id:111920, value: "Cotton Farming"},
{id:111930, value: "Sugarcane Farming"},
{id:111940, value: "Hay Farming"},
{id:111991, value: "Sugar Beet Farming"},
{id:111992, value: "Peanut Farming"},
{id:111998, value: "All Other Miscellaneous Crop Farming"},
{id:112111, value: "Beef Cattle Ranching and Farming"},
{id:112112, value: "Cattle Feedlots"},
{id:112120, value: "Dairy Cattle and Milk Production"},
{id:112130, value: "Dual-Purpose Cattle Ranching and Farming"},
{id:112210, value: "Hog and Pig Farming"},
{id:112310, value: "Chicken Egg Production"},
{id:112320, value: "Broilers and Other Meat Type Chicken Production"},
{id:112330, value: "Turkey Production"},
{id:112340, value: "Poultry Hatcheries"},
{id:112390, value: "Other Poultry Production"},
{id:112410, value: "Sheep Farming"},
{id:112420, value: "Goat Farming"},
{id:112511, value: "Finfish Farming and Fish Hatcheries"},
{id:112512, value: "Shellfish Farming"},
{id:112519, value: "Other Aquaculture"},
{id:112910, value: "Apiculture"},
{id:112920, value: "Horses and Other Equine Production"},
{id:112930, value: "Fur-Bearing Animal and Rabbit Production"},
{id:112990, value: "All Other Animal Production"},
{id:113110, value: "Timber Tract Operations"},
{id:113210, value: "Forest Nurseries and Gathering of Forest Products"},
{id:113310, value: "Logging"},
{id:114111, value: "Finfish Fishing"},
{id:114112, value: "Shellfish Fishing"},
{id:114119, value: "Other Marine Fishing"},
{id:114210, value: "Hunting and Trapping"},
{id:115111, value: "Cotton Ginning"},
{id:115112  , value: "Soil Preparation, Planting, and Cultivating"},
{id:115113  , value: "Crop Harvesting, Primarily by Machine"},
{id:115114, value: "Postharvest Crop Activities (except Cotton Ginning)"},
{id:115115, value: "Farm Labor Contractors and Crew Leaders"},
{id:115116, value: "Farm Management Services"},
{id:115210, value: "Support Activities for Animal Production"},
{id:115310, value: "Support Activities for Forestry"},
{id:211111, value: "Crude Petroleum and Natural Gas Extraction"},
{id:211112, value: "Natural Gas Liquid Extraction"},
{id:212111, value: "Bituminous Coal and Lignite Surface Mining"},
{id:212112, value: "Bituminous Coal Underground Mining"},
{id:212113, value: "Anthracite Mining"},
{id:212210, value: "Iron Ore Mining"},
{id:212221, value: "Gold Ore Mining"},
{id:212222, value: "Silver Ore Mining"},
{id:212231, value: "Lead Ore and Zinc Ore Mining"},
{id:212234, value: "Copper Ore and Nickel Ore Mining"},
{id:212291, value: "Uranium-Radium-Vanadium Ore Mining"},
{id:212299, value: "All Other Metal Ore Mining"},
{id:212311, value: "Dimension Stone Mining and Quarrying"},
{id:212312, value: "Crushed and Broken Limestone Mining and Quarrying"},
{id:212313, value: "Crushed and Broken Granite Mining and Quarrying"},
{id:212319, value: "Other Crushed and Broken Stone Mining and Quarrying"},
{id:212321, value: "Construction Sand and Gravel Mining"},
{id:212322, value: "Industrial Sand Mining"},
{id:212324, value: "Kaolin and Ball Clay Mining"},
{id:212325, value: "Clay and Ceramic and Refractory Minerals Mining"},
{id:212391  , value: "Potash, Soda, and Borate Mineral Mining"},
{id:212392, value: "Phosphate Rock Mining"},
{id:212393, value: "Other Chemical and Fertilizer Mineral Mining"},
{id:212399, value: "All Other Nonmetallic Mineral Mining"},
{id:213111, value: "Drilling Oil and Gas Wells"},
{id:213112, value: "Support Activities for Oil and Gas Operations"},
{id:213113, value: "Support Activities for Coal Mining"},
{id:213114, value: "Support Activities for Metal Mining"},
{id:213115, value: "Support Activities for Nonmetallic Minerals (except Fuels)"},
{id:221111, value: "Hydroelectric Power Generation"},
{id:221112, value: "Fossil Fuel Electric Power Generation"},
{id:221113, value: "Nuclear Electric Power Generation"},
{id:221119, value: "Other Electric Power Generation"},
{id:221121, value: "Electric Bulk Power Transmission and Control"},
{id:221122, value: "Electric Power Distribution"},
{id:221210, value: "Natural Gas Distribution"},
{id:221310, value: "Water Supply and Irrigation Systems"},
{id:221320, value: "Sewage Treatment Facilities"},
{id:221330, value: "Steam and Air-Conditioning Supply"},
{id:236115, value: "New Single-Family Housing Construction (except Operative Builders)"},
{id:236116, value: "New Multifamily Housing Construction (except Operative Builders)"},
{id:236117, value: "New Housing Operative Builders"},
{id:236118, value: "Residential Remodelers"},
{id:236210, value: "Industrial Building Construction"},
{id:236220, value: "Commercial and Institutional Building Construction"},
{id:237110, value: "Water and Sewer Line and Related Structures Construction"},
{id:237120, value: "Oil and Gas Pipeline and Related Structures Construction"},
{id:237130, value: "Power and Communication Line and Related Structures Construction"},
{id:237210, value: "Land Subdivision"},
{id:237310  , value: "Highway, Street, and Bridge Construction"},
{id:237990, value: "Other Heavy and Civil Engineering Construction"},
{id:238110, value: "Poured Concrete Foundation and Structure Contractors"},
{id:238120, value: "Structural Steel and Precast Concrete Contractors"},
{id:238130, value: "Framing Contractors"},
{id:238140, value: "Masonry Contractors"},
{id:238150, value: "Glass and Glazing Contractors"},
{id:238160, value: "Roofing Contractors"},
{id:238170, value: "Siding Contractors"},
{id:238190  , value: "Other Foundation, Structure, and Building Exterior Contractors"},
{id:238210, value: "Electrical Contractors and Other Wiring Installation Contractors"},
{id:238220  , value: "Plumbing, Heating, and Air-Conditioning Contractors"},
{id:238290, value: "Other Building Equipment Contractors"},
{id:238310, value: "Drywall and Insulation Contractors"},
{id:238320, value: "Painting and Wall Covering Contractors"},
{id:238330, value: "Flooring Contractors"},
{id:238340, value: "Tile and Terrazzo Contractors"},
{id:238350, value: "Finish Carpentry Contractors"},
{id:238390, value: "Other Building Finishing Contractors"},
{id:238910, value: "Site Preparation Contractors"},
{id:238990, value: "All Other Specialty Trade Contractors"},
{id:311111, value: "Dog and Cat Food Manufacturing"},
{id:311119, value: "Other Animal Food Manufacturing"},
{id:311211, value: "Flour Milling"},
{id:311212, value: "Rice Milling"},
{id:311213, value: "Malt Manufacturing"},
{id:311221, value: "Wet Corn Milling"},
{id:311222, value: "Soybean Processing"},
{id:311223, value: "Other Oilseed Processing"},
{id:311225, value: "Fats and Oils Refining and Blending"},
{id:311230, value: "Breakfast Cereal Manufacturing"},
{id:311311, value: "Sugarcane Mills"},
{id:311312, value: "Cane Sugar Refining"},
{id:311313, value: "Beet Sugar Manufacturing"},
{id:311320, value: "Chocolate and Confectionery Manufacturing from Cacao Beans"},
{id:311330, value: "Confectionery Manufacturing from Purchased Chocolate"},
{id:311340, value: "Nonchocolate Confectionery Manufacturing"},
{id:311411  , value: "Frozen Fruit, Juice, and Vegetable Manufacturing"},
{id:311412, value: "Frozen Specialty Food Manufacturing"},
{id:311421, value: "Fruit and Vegetable Canning"},
{id:311422, value: "Specialty Canning"},
{id:311423, value: "Dried and Dehydrated Food Manufacturing"},
{id:311511, value: "Fluid Milk Manufacturing"},
{id:311512, value: "Creamery Butter Manufacturing"},
{id:311513, value: "Cheese Manufacturing"},
{id:311514  , value: "Dry, Condensed, and Evaporated Dairy Product Manufacturing"},
{id:311520, value: "Ice Cream and Frozen Dessert Manufacturing"},
{id:311611, value: "Animal (except Poultry) Slaughtering"},
{id:311612, value: "Meat Processed from Carcasses"},
{id:311613, value: "Rendering and Meat Byproduct Processing"},
{id:311615, value: "Poultry Processing"},
{id:311711, value: "Seafood Canning"},
{id:311712, value: "Fresh and Frozen Seafood Processing"},
{id:311811, value: "Retail Bakeries"},
{id:311812, value: "Commercial Bakeries"},
{id:311813  , value: "Frozen Cakes, Pies, and Other Pastries Manufacturing"},
{id:311821, value: "Cookie and Cracker Manufacturing"},
{id:311822, value: "Flour Mixes and Dough Manufacturing from Purchased Flour"},
{id:311823, value: "Dry Pasta Manufacturing"},
{id:311830, value: "Tortilla Manufacturing"},
{id:311911, value: "Roasted Nuts and Peanut Butter Manufacturing"},
{id:311919, value: "Other Snack Food Manufacturing"},
{id:311920, value: "Coffee and Tea Manufacturing"},
{id:311930, value: "Flavoring Syrup and Concentrate Manufacturing"},
{id:311941  , value: "Mayonnaise, Dressing, and Other Prepared Sauce Manufacturing"},
{id:311942, value: "Spice and Extract Manufacturing"},
{id:311991, value: "Perishable Prepared Food Manufacturing"},
{id:311999, value: "All Other Miscellaneous Food Manufacturing"},
{id:312111, value: "Soft Drink Manufacturing"},
{id:312112, value: "Bottled Water Manufacturing"},
{id:312113, value: "Ice Manufacturing"},
{id:312120, value: "Breweries"},
{id:312130, value: "Wineries"},
{id:312140, value: "Distilleries"},
{id:312210, value: "Tobacco Stemming and Redrying"},
{id:312221, value: "Cigarette Manufacturing"},
{id:312229, value: "Other Tobacco Product Manufacturing"},
{id:313111, value: "Yarn Spinning Mills"},
{id:313112  , value: "Yarn Texturizing, Throwing, and Twisting Mills"},
{id:313113, value: "Thread Mills"},
{id:313210, value: "Broadwoven Fabric Mills"},
{id:313221, value: "Narrow Fabric Mills"},
{id:313222, value: "Schiffli Machine Embroidery"},
{id:313230, value: "Nonwoven Fabric Mills"},
{id:313241, value: "Weft Knit Fabric Mills"},
{id:313249, value: "Other Knit Fabric and Lace Mills"},
{id:313311, value: "Broadwoven Fabric Finishing Mills"},
{id:313312, value: "Textile and Fabric Finishing (except Broadwoven Fabric) Mills"},
{id:313320, value: "Fabric Coating Mills"},
{id:314110, value: "Carpet and Rug Mills"},
{id:314121, value: "Curtain and Drapery Mills"},
{id:314129, value: "Other Household Textile Product Mills"},
{id:314911, value: "Textile Bag Mills"},
{id:314912, value: "Canvas and Related Product Mills"},
{id:314991  , value: "Rope, Cordage, and Twine Mills"},
{id:314992, value: "Tire Cord and Tire Fabric Mills"},
{id:314999, value: "All Other Miscellaneous Textile Product Mills"},
{id:315111, value: "Sheer Hosiery Mills"},
{id:315119, value: "Other Hosiery and Sock Mills"},
{id:315191, value: "Outerwear Knitting Mills"},
{id:315192, value: "Underwear and Nightwear Knitting Mills"},
{id:315211, value: "Men's and Boys' Cut and Sew Apparel Contractors"},
{id:315212 , value: "Women's, Girls', and Infants' Cut and Sew Apparel Contractors"},
{id:315221, value: "Men's and Boys' Cut and Sew Underwear and Nightwear Manufacturing"},
{id:315222  , value: "Men's and Boys' Cut and Sew Suit, Coat, and Overcoat Manufacturing"},
{id:315223, value: "Men's and Boys' Cut and Sew Shirt (except Work Shirt) Manufacturing"},
{id:315224  , value: "Men's and Boys' Cut and Sew Trouser, Slack, and Jean Manufacturing"},
{id:315225, value: "Men's and Boys' Cut and Sew Work Clothing Manufacturing"},
{id:315228, value: "Men's and Boys' Cut and Sew Other Outerwear Manufacturing"},
{id:315231  , value: "Women's and Girls' Cut and Sew Lingerie, Loungewear, and Nightwear Manufacturing"},
{id:315232, value: "Women's and Girls' Cut and Sew Blouse and Shirt Manufacturing"},
{id:315233, value: "Women's and Girls' Cut and Sew Dress Manufacturing"},
{id:315234  , value: "Women's and Girls' Cut and Sew Suit, Coat, Tailored Jacket, and Skirt Manufacturing"},
{id:315239, value: "Women's and Girls' Cut and Sew Other Outerwear Manufacturing"},
{id:315291, value: "Infants' Cut and Sew Apparel Manufacturing"},
{id:315292, value: "Fur and Leather Apparel Manufacturing"},
{id:315299, value: "All Other Cut and Sew Apparel Manufacturing"},
{id:315991  , value: "Hat, Cap, and Millinery Manufacturing"},
{id:315992, value: "Glove and Mitten Manufacturing"},
{id:315993, value: "Men's and Boys' Neckwear Manufacturing"},
{id:315999, value: "Other Apparel Accessories and Other Apparel Manufacturing"},
{id:316110, value: "Leather and Hide Tanning and Finishing"},
{id:316211, value: "Rubber and Plastics Footwear Manufacturing"},
{id:316212, value: "House Slipper Manufacturing"},
{id:316213, value: "Men's Footwear (except Athletic) Manufacturing"},
{id:316214, value: "Women's Footwear (except Athletic) Manufacturing"},
{id:316219, value: "Other Footwear Manufacturing"},
{id:316991, value: "Luggage Manufacturing"},
{id:316992, value: "Women's Handbag and Purse Manufacturing"},
{id:316993, value: "Personal Leather Good (except Women's Handbag and Purse) Manufacturing"},
{id:316999, value: "All Other Leather Good and Allied Product Manufacturing"},
{id:321113, value: "Sawmills"},
{id:321114, value: "Wood Preservation"},
{id:321211, value: "Hardwood Veneer and Plywood Manufacturing"},
{id:321212, value: "Softwood Veneer and Plywood Manufacturing"},
{id:321213, value: "Engineered Wood Member (except Truss) Manufacturing"},
{id:321214, value: "Truss Manufacturing"},
{id:321219, value: "Reconstituted Wood Product Manufacturing"},
{id:321911, value: "Wood Window and Door Manufacturing"},
{id:321912  , value: "Cut Stock, Resawing Lumber, and Planing"},
{id:321918, value: "Other Millwork (including Flooring)"},
{id:321920, value: "Wood Container and Pallet Manufacturing"},
{id:321991, value: "Manufactured Home (Mobile Home) Manufacturing"},
{id:321992, value: "Prefabricated Wood Building Manufacturing"},
{id:321999, value: "All Other Miscellaneous Wood Product Manufacturing"},
{id:322110, value: "Pulp Mills"},
{id:322121, value: "Paper (except Newsprint) Mills"},
{id:322122, value: "Newsprint Mills"},
{id:322130, value: "Paperboard Mills"},
{id:322211, value: "Corrugated and Solid Fiber Box Manufacturing"},
{id:322212, value: "Folding Paperboard Box Manufacturing"},
{id:322213, value: "Setup Paperboard Box Manufacturing"},
{id:322214  , value: "Fiber Can, Tube, Drum, and Similar Products Manufacturing"},
{id:322215, value: "Nonfolding Sanitary Food Container Manufacturing"},
{id:322221, value: "Coated and Laminated Packaging Paper Manufacturing"},
{id:322222, value: "Coated and Laminated Paper Manufacturing"},
{id:322223  , value: "Coated Paper Bag and Pouch Manufacturing"},
{id:322224, value: "Uncoated Paper and Multiwall Bag Manufacturing"},
{id:322225, value: "Laminated Aluminum Foil Manufacturing for Flexible Packaging Uses"},
{id:322226, value: "Surface-Coated Paperboard Manufacturing"},
{id:322231, value: "Die-Cut Paper and Paperboard Office Supplies Manufacturing"},
{id:322232, value: "Envelope Manufacturing"},
{id:322233  , value: "Stationery, Tablet, and Related Product Manufacturing"},
{id:322291, value: "Sanitary Paper Product Manufacturing"},
{id:322299, value: "All Other Converted Paper Product Manufacturing"},
{id:323110, value: "Commercial Lithographic Printing"},
{id:323111, value: "Commercial Gravure Printing"},
{id:323112, value: "Commercial Flexographic Printing"},
{id:323113, value: "Commercial Screen Printing"},
{id:323114, value: "Quick Printing"},
{id:323115, value: "Digital Printing"},
{id:323116, value: "Manifold Business Forms Printing"},
{id:323117, value: "Books Printing"},
{id:323118  , value: "Blankbook, Looseleaf Binders, and Devices Manufacturing"},
{id:323119, value: "Other Commercial Printing"},
{id:323121, value: "Tradebinding and Related Work"},
{id:323122, value: "Prepress Services"},
{id:324110, value: "Petroleum Refineries"},
{id:324121, value: "Asphalt Paving Mixture and Block Manufacturing"},
{id:324122, value: "Asphalt Shingle and Coating Materials Manufacturing"},
{id:324191, value: "Petroleum Lubricating Oil and Grease Manufacturing"},
{id:324199, value: "All Other Petroleum and Coal Products Manufacturing"},
{id:325110, value: "Petrochemical Manufacturing"},
{id:325120, value: "Industrial Gas Manufacturing"},
{id:325131, value: "Inorganic Dye and Pigment Manufacturing"},
{id:325132, value: "Synthetic Organic Dye and Pigment Manufacturing"},
{id:325181, value: "Alkalies and Chlorine Manufacturing"},
{id:325182, value: "Carbon Black Manufacturing"},
{id:325188, value: "All Other Basic Inorganic Chemical Manufacturing"},
{id:325191, value: "Gum and Wood Chemical Manufacturing"},
{id:325192, value: "Cyclic Crude and Intermediate Manufacturing"},
{id:325193, value: "Ethyl Alcohol Manufacturing"},
{id:325199, value: "All Other Basic Organic Chemical Manufacturing"},
{id:325211, value: "Plastics Material and Resin Manufacturing"},
{id:325212, value: "Synthetic Rubber Manufacturing"},
{id:325221, value: "Cellulosic Organic Fiber Manufacturing"},
{id:325222, value: "Noncellulosic Organic Fiber Manufacturing"},
{id:325311, value: "Nitrogenous Fertilizer Manufacturing"},
{id:325312, value: "Phosphatic Fertilizer Manufacturing"},
{id:325314, value: "Fertilizer (Mixing Only) Manufacturing"},
{id:325320, value: "Pesticide and Other Agricultural Chemical Manufacturing"},
{id:325411, value: "Medicinal and Botanical Manufacturing"},
{id:325412, value: "Pharmaceutical Preparation Manufacturing"},
{id:325413, value: "In-Vitro Diagnostic Substance Manufacturing"},
{id:325414, value: "Biological Product (except Diagnostic) Manufacturing"},
{id:325510, value: "Paint and Coating Manufacturing"},
{id:325520, value: "Adhesive Manufacturing"},
{id:325611, value: "Soap and Other Detergent Manufacturing"},
{id:325612, value: "Polish and Other Sanitation Good Manufacturing"},
{id:325613, value: "Surface Active Agent Manufacturing"},
{id:325620, value: "Toilet Preparation Manufacturing"},
{id:325910, value: "Printing Ink Manufacturing"},
{id:325920, value: "Explosives Manufacturing"},
{id:325991, value: "Custom Compounding of Purchased Resins"},
{id:325992  , value: "Photographic Film, Paper, Plate, and Chemical Manufacturing"},
{id:325998, value: "All Other Miscellaneous Chemical Product and Preparation Manufacturing"},
{id:326111, value: "Plastics Bag and Pouch Manufacturing"},
{id:326112, value: "Plastics Packaging Film and Sheet (including Laminated) Manufacturing"},
{id:326113, value: "Unlaminated Plastics Film and Sheet (except Packaging) Manufacturing"},
{id:326121, value: "Unlaminated Plastics Profile Shape Manufacturing"},
{id:326122, value: "Plastics Pipe and Pipe Fitting Manufacturing"},
{id:326130  , value: "Laminated Plastics Plate, Sheet (except Packaging), and Shape Manufacturing"},
{id:326140, value: "Polystyrene Foam Product Manufacturing"},
{id:326150, value: "Urethane and Other Foam Product (except Polystyrene) Manufacturing"},
{id:326160, value: "Plastics Bottle Manufacturing"},
{id:326191, value: "Plastics Plumbing Fixture Manufacturing"},
{id:326192, value: "Resilient Floor Covering Manufacturing"},
{id:326199, value: "All Other Plastics Product Manufacturing"},
{id:326211, value: "Tire Manufacturing (except Retreading)"},
{id:326212, value: "Tire Retreading"},
{id:326220, value: "Rubber and Plastics Hoses and Belting Manufacturing"},
{id:326291, value: "Rubber Product Manufacturing for Mechanical Use"},
{id:326299, value: "All Other Rubber Product Manufacturing"},
{id:327111, value: "Vitreous China Plumbing Fixture and China and Earthenware Bathroom Accessories Manufacturing"},
{id:327112  , value: "Vitreous China, Fine Earthenware, and Other Pottery Product Manufacturing"},
{id:327113, value: "Porcelain Electrical Supply Manufacturing"},
{id:327121, value: "Brick and Structural Clay Tile Manufacturing"},
{id:327122, value: "Ceramic Wall and Floor Tile Manufacturing"},
{id:327123, value: "Other Structural Clay Product Manufacturing"},
{id:327124, value: "Clay Refractory Manufacturing"},
{id:327125, value: "Nonclay Refractory Manufacturing"},
{id:327211, value: "Flat Glass Manufacturing"},
{id:327212, value: "Other Pressed and Blown Glass and Glassware Manufacturing"},
{id:327213, value: "Glass Container Manufacturing"},
{id:327215, value: "Glass Product Manufacturing Made of Purchased Glass"},
{id:327310, value: "Cement Manufacturing"},
{id:327320, value: "Ready-Mix Concrete Manufacturing"},
{id:327331, value: "Concrete Block and Brick Manufacturing"},
{id:327332, value: "Concrete Pipe Manufacturing"},
{id:327390, value: "Other Concrete Product Manufacturing"},
{id:327410, value: "Lime Manufacturing"},
{id:327420, value: "Gypsum Product Manufacturing"},
{id:327910, value: "Abrasive Product Manufacturing"},
{id:327991, value: "Cut Stone and Stone Product Manufacturing"},
{id:327992, value: "Ground or Treated Mineral and Earth Manufacturing"},
{id:327993, value: "Mineral Wool Manufacturing"},
{id:327999, value: "All Other Miscellaneous Nonmetallic Mineral Product Manufacturing"},
{id:331111, value: "Iron and Steel Mills"},
{id:331112, value: "Electrometallurgical Ferroalloy Product Manufacturing"},
{id:331210, value: "Iron and Steel Pipe and Tube Manufacturing from Purchased Steel"},
{id:331221, value: "Rolled Steel Shape Manufacturing"},
{id:331222, value: "Steel Wire Drawing"},
{id:331311, value: "Alumina Refining"},
{id:331312, value: "Primary Aluminum Production"},
{id:331314, value: "Secondary Smelting and Alloying of Aluminum"},
{id:331315 , value: "Aluminum Sheet, Plate, and Foil Manufacturing"},
{id:331316, value: "Aluminum Extruded Product Manufacturing"},
{id:331319, value: "Other Aluminum Rolling and Drawing"},
{id:331411, value: "Primary Smelting and Refining of Copper"},
{id:331419, value: "Primary Smelting and Refining of Nonferrous Metal (except Copper and Aluminum)"},
{id:331421  , value: "Copper Rolling, Drawing, and Extruding"},
{id:331422, value: "Copper Wire (except Mechanical) Drawing"},
{id:331423  , value: "Secondary Smelting, Refining, and Alloying of Copper"},
{id:331491  , value: "Nonferrous Metal (except Copper and Aluminum) Rolling, Drawing, and Extruding"},
{id:331492  , value: "Secondary Smelting, Refining, and Alloying of Nonferrous Metal (except Copper and Aluminum)"},
{id:331511, value: "Iron Foundries"},
{id:331512, value: "Steel Investment Foundries"},
{id:331513, value: "Steel Foundries (except Investment)"},
{id:331521, value: "Aluminum Die-Casting Foundries"},
{id:331522, value: "Nonferrous (except Aluminum) Die-Casting Foundries"},
{id:331524, value: "Aluminum Foundries (except Die-Casting)"},
{id:331525, value: "Copper Foundries (except Die-Casting)"},
{id:331528, value: "Other Nonferrous Foundries (except Die-Casting)"},
{id:332111, value: "Iron and Steel Forging"},
{id:332112, value: "Nonferrous Forging"},
{id:332114, value: "Custom Roll Forming"},
{id:332115, value: "Crown and Closure Manufacturing"},
{id:332116, value: "Metal Stamping"},
{id:332117, value: "Powder Metallurgy Part Manufacturing"},
{id:332211, value: "Cutlery and Flatware (except Precious) Manufacturing"},
{id:332212, value: "Hand and Edge Tool Manufacturing"},
{id:332213, value: "Saw Blade and Handsaw Manufacturing"},
{id:332214  , value: "Kitchen Utensil, Pot, and Pan Manufacturing"},
{id:332311, value: "Prefabricated Metal Building and Component Manufacturing"},
{id:332312, value: "Fabricated Structural Metal Manufacturing"},
{id:332313, value: "Plate Work Manufacturing"},
{id:332321, value: "Metal Window and Door Manufacturing"},
{id:332322, value: "Sheet Metal Work Manufacturing"},
{id:332323, value: "Ornamental and Architectural Metal Work Manufacturing"},
{id:332410, value: "Power Boiler and Heat Exchanger Manufacturing"},
{id:332420, value: "Metal Tank (Heavy Gauge) Manufacturing"},
{id:332431, value: "Metal Can Manufacturing"},
{id:332439, value: "Other Metal Container Manufacturing"},
{id:332510, value: "Hardware Manufacturing"},
{id:332611, value: "Spring (Heavy Gauge) Manufacturing"},
{id:332612, value: "Spring (Light Gauge) Manufacturing"},
{id:332618, value: "Other Fabricated Wire Product Manufacturing"},
{id:332710, value: "Machine Shops"},
{id:332721, value: "Precision Turned Product Manufacturing"},
{id:332722  , value: "Bolt, Nut, Screw, Rivet, and Washer Manufacturing"},
{id:332811, value: "Metal Heat Treating"},
{id:332812  , value: "Metal Coating, Engraving (except Jewelry and Silverware), and Allied Services to Manufacturers"},
{id:332813  , value: "Electroplating, Plating, Polishing, Anodizing, and Coloring"},
{id:332911, value: "Industrial Valve Manufacturing"},
{id:332912, value: "Fluid Power Valve and Hose Fitting Manufacturing"},
{id:332913, value: "Plumbing Fixture Fitting and Trim Manufacturing"},
{id:332919, value: "Other Metal Valve and Pipe Fitting Manufacturing"},
{id:332991, value: "Ball and Roller Bearing Manufacturing"},
{id:332992, value: "Small Arms Ammunition Manufacturing"},
{id:332993, value: "Ammunition (except Small Arms) Manufacturing"},
{id:332994, value: "Small Arms Manufacturing"},
{id:332995, value: "Other Ordnance and Accessories Manufacturing"},
{id:332996, value: "Fabricated Pipe and Pipe Fitting Manufacturing"},
{id:332997, value: "Industrial Pattern Manufacturing"},
{id:332998, value: "Enameled Iron and Metal Sanitary Ware Manufacturing"},
{id:332999, value: "All Other Miscellaneous Fabricated Metal Product Manufacturing"},
{id:333111, value: "Farm Machinery and Equipment Manufacturing"},
{id:333112, value: "Lawn and Garden Tractor and Home Lawn and Garden Equipment Manufacturing"},
{id:333120, value: "Construction Machinery Manufacturing"},
{id:333131, value: "Mining Machinery and Equipment Manufacturing"},
{id:333132, value: "Oil and Gas Field Machinery and Equipment Manufacturing"},
{id:333210, value: "Sawmill and Woodworking Machinery Manufacturing"},
{id:333220, value: "Plastics and Rubber Industry Machinery Manufacturing"},
{id:333291, value: "Paper Industry Machinery Manufacturing"},
{id:333292, value: "Textile Machinery Manufacturing"},
{id:333293, value: "Printing Machinery and Equipment Manufacturing"},
{id:333294, value: "Food Product Machinery Manufacturing"},
{id:333295, value: "Semiconductor Machinery Manufacturing"},
{id:333298, value: "All Other Industrial Machinery Manufacturing"},
{id:333311, value: "Automatic Vending Machine Manufacturing"},
{id:333312  , value: "Commercial Laundry, Drycleaning, and Pressing Machine Manufacturing"},
{id:333313, value: "Office Machinery Manufacturing"},
{id:333314, value: "Optical Instrument and Lens Manufacturing"},
{id:333315, value: "Photographic and Photocopying Equipment Manufacturing"},
{id:333319, value: "Other Commercial and Service Industry Machinery Manufacturing"},
{id:333411, value: "Air Purification Equipment Manufacturing"},
{id:333412, value: "Industrial and Commercial Fan and Blower Manufacturing"},
{id:333414, value: "Heating Equipment (except Warm Air Furnaces) Manufacturing"},
{id:333415, value: "Air-Conditioning and Warm Air Heating Equipment and Commercial and Industrial Refrigeration Equipment Manufacturing"},
{id:333511, value: "Industrial Mold Manufacturing"},
{id:333512, value: "Machine Tool (Metal Cutting Types) Manufacturing"},
{id:333513, value: "Machine Tool (Metal Forming Types) Manufacturing"},
{id:333514  , value: "Special Die and Tool, Die Set, Jig, and Fixture Manufacturing"},
{id:333515, value: "Cutting Tool and Machine Tool Accessory Manufacturing"},
{id:333516, value: "Rolling Mill Machinery and Equipment Manufacturing"},
{id:333518, value: "Other Metalworking Machinery Manufacturing"},
{id:333611, value: "Turbine and Turbine Generator Set Units Manufacturing"},
{id:333612  , value: "Speed Changer, Industrial High-Speed Drive, and Gear Manufacturing"},
{id:333613, value: "Mechanical Power Transmission Equipment Manufacturing"},
{id:333618, value: "Other Engine Equipment Manufacturing"},
{id:333911, value: "Pump and Pumping Equipment Manufacturing"},
{id:333912, value: "Air and Gas Compressor Manufacturing"},
{id:333913, value: "Measuring and Dispensing Pump Manufacturing"},
{id:333921, value: "Elevator and Moving Stairway Manufacturing"},
{id:333922, value: "Conveyor and Conveying Equipment Manufacturing"},
{id:333923  , value: "Overhead Traveling Crane, Hoist, and Monorail System Manufacturing"},
{id:333924 , value: "Industrial Truck, Tractor, Trailer, and Stacker Machinery Manufacturing"},
{id:333991, value: "Power-Driven Handtool Manufacturing"},
{id:333992, value: "Welding and Soldering Equipment Manufacturing"},
{id:333993, value: "Packaging Machinery Manufacturing"},
{id:333994, value: "Industrial Process Furnace and Oven Manufacturing"},
{id:333995, value: "Fluid Power Cylinder and Actuator Manufacturing"},
{id:333996, value: "Fluid Power Pump and Motor Manufacturing"},
{id:333997, value: "Scale and Balance Manufacturing"},
{id:333999, value: "All Other Miscellaneous General Purpose Machinery Manufacturing"},
{id:334111, value: "Electronic Computer Manufacturing"},
{id:334112, value: "Computer Storage Device Manufacturing"},
{id:334113, value: "Computer Terminal Manufacturing"},
{id:334119, value: "Other Computer Peripheral Equipment Manufacturing"},
{id:334210, value: "Telephone Apparatus Manufacturing"},
{id:334220, value: "Radio and Television Broadcasting and Wireless Communications Equipment Manufacturing"},
{id:334290, value: "Other Communications Equipment Manufacturing"},
{id:334310, value: "Audio and Video Equipment Manufacturing"},
{id:334411, value: "Electron Tube Manufacturing"},
{id:334412, value: "Bare Printed Circuit Board Manufacturing"},
{id:334413, value: "Semiconductor and Related Device Manufacturing"},
{id:334414, value: "Electronic Capacitor Manufacturing"},
{id:334415, value: "Electronic Resistor Manufacturing"},
{id:334416  , value: "Electronic Coil, Transformer, and Other Inductor Manufacturing"},
{id:334417, value: "Electronic Connector Manufacturing"},
{id:334418, value: "Printed Circuit Assembly (Electronic Assembly) Manufacturing"},
{id:334419, value: "Other Electronic Component Manufacturing"},
{id:334510, value: "Electromedical and Electrotherapeutic Apparatus Manufacturing"},
{id:334511  , value: "Search, Detection, Navigation, Guidance, Aeronautical, and Nautical System and Instrument Manufacturing"},
{id:334512  , value: "Automatic Environmental Control Manufacturing for Residential, Commercial, and Appliance Use"},
{id:334513 , value: "Instruments and Related Products Manufacturing for Measuring, Displaying, and Controlling Industrial Process Variables"},
{id:334514, value: "Totalizing Fluid Meter and Counting Device Manufacturing"},
{id:334515, value: "Instrument Manufacturing for Measuring and Testing Electricity and Electrical Signals"},
{id:334516, value: "Analytical Laboratory Instrument Manufacturing"},
{id:334517, value: "Irradiation Apparatus Manufacturing"},
{id:334518  , value: "Watch, Clock, and Part Manufacturing"},
{id:334519, value: "Other Measuring and Controlling Device Manufacturing"},
{id:334611, value: "Software Reproducing"},
{id:334612  , value: "Prerecorded Compact Disc (except Software), Tape, and Record Reproducing"},
{id:334613, value: "Magnetic and Optical Recording Media Manufacturing"},
{id:335110, value: "Electric Lamp Bulb and Part Manufacturing"},
{id:335121, value: "Residential Electric Lighting Fixture Manufacturing"},
{id:335122  , value: "Commercial, Industrial, and Institutional Electric Lighting Fixture Manufacturing"},
{id:335129, value: "Other Lighting Equipment Manufacturing"},
{id:335211, value: "Electric Housewares and Household Fan Manufacturing"},
{id:335212, value: "Household Vacuum Cleaner Manufacturing"},
{id:335221, value: "Household Cooking Appliance Manufacturing"},
{id:335222, value: "Household Refrigerator and Home Freezer Manufacturing"},
{id:335224, value: "Household Laundry Equipment Manufacturing"},
{id:335228, value: "Other Major Household Appliance Manufacturing"},
{id:335311  , value: "Power, Distribution, and Specialty Transformer Manufacturing"},
{id:335312, value: "Motor and Generator Manufacturing"},
{id:335313, value: "Switchgear and Switchboard Apparatus Manufacturing"},
{id:335314, value: "Relay and Industrial Control Manufacturing"},
{id:335911, value: "Storage Battery Manufacturing"},
{id:335912, value: "Primary Battery Manufacturing"},
{id:335921, value: "Fiber Optic Cable Manufacturing"},
{id:335929, value: "Other Communication and Energy Wire Manufacturing"},
{id:335931, value: "Current-Carrying Wiring Device Manufacturing"},
{id:335932, value: "Noncurrent-Carrying Wiring Device Manufacturing"},
{id:335991, value: "Carbon and Graphite Product Manufacturing"},
{id:335999, value: "All Other Miscellaneous Electrical Equipment and Component Manufacturing"},
{id:336111, value: "Automobile Manufacturing"},
{id:336112, value: "Light Truck and Utility Vehicle Manufacturing"},
{id:336120, value: "Heavy Duty Truck Manufacturing"},
{id:336211, value: "Motor Vehicle Body Manufacturing"},
{id:336212, value: "Truck Trailer Manufacturing"},
{id:336213, value: "Motor Home Manufacturing"},
{id:336214, value: "Travel Trailer and Camper Manufacturing"},
{id:336311  , value: "Carburetor, Piston, Piston Ring, and Valve Manufacturing"},
{id:336312, value: "Gasoline Engine and Engine Parts Manufacturing"},
{id:336321, value: "Vehicular Lighting Equipment Manufacturing"},
{id:336322, value: "Other Motor Vehicle Electrical and Electronic Equipment Manufacturing"},
{id:336330, value: "Motor Vehicle Steering and Suspension Components (except Spring) Manufacturing"},
{id:336340, value: "Motor Vehicle Brake System Manufacturing"},
{id:336350, value: "Motor Vehicle Transmission and Power Train Parts Manufacturing"},
{id:336360, value: "Motor Vehicle Seating and Interior Trim Manufacturing"},
{id:336370, value: "Motor Vehicle Metal Stamping"},
{id:336391, value: "Motor Vehicle Air-Conditioning Manufacturing"},
{id:336399, value: "All Other Motor Vehicle Parts Manufacturing"},
{id:336411, value: "Aircraft Manufacturing"},
{id:336412, value: "Aircraft Engine and Engine Parts Manufacturing"},
{id:336413, value: "Other Aircraft Parts and Auxiliary Equipment Manufacturing"},
{id:336414, value: "Guided Missile and Space Vehicle Manufacturing"},
{id:336415, value: "Guided Missile and Space Vehicle Propulsion Unit and Propulsion Unit Parts Manufacturing"},
{id:336419, value: "Other Guided Missile and Space Vehicle Parts and Auxiliary Equipment Manufacturing"},
{id:336510, value: "Railroad Rolling Stock Manufacturing"},
{id:336611, value: "Ship Building and Repairing"},
{id:336612, value: "Boat Building"},
{id:336991  , value: "Motorcycle, Bicycle, and Parts Manufacturing"},
{id:336992  , value: "Military Armored Vehicle, Tank, and Tank Component Manufacturing"},
{id:336999, value: "All Other Transportation Equipment Manufacturing"},
{id:337110, value: "Wood Kitchen Cabinet and Countertop Manufacturing"},
{id:337121, value: "Upholstered Household Furniture Manufacturing"},
{id:337122, value: "Nonupholstered Wood Household Furniture Manufacturing"},
{id:337124, value: "Metal Household Furniture Manufacturing"},
{id:337125, value: "Household Furniture (except Wood and Metal) Manufacturing"},
{id:337127, value: "Institutional Furniture Manufacturing"},
{id:337129  , value: "Wood Television, Radio, and Sewing Machine Cabinet Manufacturing"},
{id:337211, value: "Wood Office Furniture Manufacturing"},
{id:337212, value: "Custom Architectural Woodwork and Millwork Manufacturing"},
{id:337214, value: "Office Furniture (except Wood) Manufacturing"},
{id:337215  , value: "Showcase, Partition, Shelving, and Locker Manufacturing"},
{id:337910, value: "Mattress Manufacturing"},
{id:337920, value: "Blind and Shade Manufacturing"},
{id:339112, value: "Surgical and Medical Instrument Manufacturing"},
{id:339113, value: "Surgical Appliance and Supplies Manufacturing"},
{id:339114, value: "Dental Equipment and Supplies Manufacturing"},
{id:339115, value: "Ophthalmic Goods Manufacturing"},
{id:339116, value: "Dental Laboratories"},
{id:339911, value: "Jewelry (except Costume) Manufacturing"},
{id:339912, value: "Silverware and Hollowware Manufacturing"},
{id:339913, value: "Jewelers' Material and Lapidary Work Manufacturing"},
{id:339914, value: "Costume Jewelry and Novelty Manufacturing"},
{id:339920, value: "Sporting and Athletic Goods Manufacturing"},
{id:339931, value: "Doll and Stuffed Toy Manufacturing"},
{id:339932  , value: "Game, Toy, and Children's Vehicle Manufacturing"},
{id:339941, value: "Pen and Mechanical Pencil Manufacturing"},
{id:339942, value: "Lead Pencil and Art Good Manufacturing"},
{id:339943, value: "Marking Device Manufacturing"},
{id:339944, value: "Carbon Paper and Inked Ribbon Manufacturing"},
{id:339950, value: "Sign Manufacturing"},
{id:339991  , value: "Gasket, Packing, and Sealing Device Manufacturing"},
{id:339992, value: "Musical Instrument Manufacturing"},
{id:339993  , value: "Fastener, Button, Needle, and Pin Manufacturing"},
{id:339994  , value: "Broom, Brush, and Mop Manufacturing"},
{id:339995, value: "Burial Casket Manufacturing"},
{id:339999, value: "All Other Miscellaneous Manufacturing"},
{id:423110, value: "Automobile and Other Motor Vehicle Merchant Wholesalers"},
{id:423120, value: "Motor Vehicle Supplies and New Parts Merchant Wholesalers"},
{id:423130, value: "Tire and Tube Merchant Wholesalers"},
{id:423140, value: "Motor Vehicle Parts (Used) Merchant Wholesalers"},
{id:423210, value: "Furniture Merchant Wholesalers"},
{id:423220, value: "Home Furnishing Merchant Wholesalers"},
{id:423310  , value: "Lumber, Plywood, Millwork, and Wood Panel Merchant Wholesalers"},
{id:423320  , value: "Brick, Stone, and Related Construction Material Merchant Wholesalers"},
{id:423330  , value: "Roofing, Siding, and Insulation Material Merchant Wholesalers"},
{id:423390, value: "Other Construction Material Merchant Wholesalers"},
{id:423410, value: "Photographic Equipment and Supplies Merchant Wholesalers"},
{id:423420, value: "Office Equipment Merchant Wholesalers"},
{id:423430, value: "Computer and Computer Peripheral Equipment and Software Merchant Wholesalers"},
{id:423440, value: "Other Commercial Equipment Merchant Wholesalers"},
{id:423450  , value: "Medical, Dental, and Hospital Equipment and Supplies Merchant Wholesalers"},
{id:423460, value: "Ophthalmic Goods Merchant Wholesalers"},
{id:423490, value: "Other Professional Equipment and Supplies Merchant Wholesalers"},
{id:423510, value: "Metal Service Centers and Other Metal Merchant Wholesalers"},
{id:423520, value: "Coal and Other Mineral and Ore Merchant Wholesalers"},
{id:423610  , value: "Electrical Apparatus and Equipment, Wiring Supplies, and Related Equipment Merchant Wholesalers"},
{id:423620  , value: "Electrical and Electronic Appliance, Television, and Radio Set Merchant Wholesalers"},
{id:423690, value: "Other Electronic Parts and Equipment Merchant Wholesalers"},
{id:423710, value: "Hardware Merchant Wholesalers"},
{id:423720, value: "Plumbing and Heating Equipment and Supplies (Hydronics) Merchant Wholesalers"},
{id:423730, value: "Warm Air Heating and Air-Conditioning Equipment and Supplies Merchant Wholesalers"},
{id:423740, value: "Refrigeration Equipment and Supplies Merchant Wholesalers"},
{id:423810, value: "Construction and Mining (except Oil Well) Machinery and Equipment Merchant Wholesalers"},
{id:423820, value: "Farm and Garden Machinery and Equipment Merchant Wholesalers"},
{id:423830, value: "Industrial Machinery and Equipment Merchant Wholesalers"},
{id:423840, value: "Industrial Supplies Merchant Wholesalers"},
{id:423850, value: "Service Establishment Equipment and Supplies Merchant Wholesalers"},
{id:423860, value: "Transportation Equipment and Supplies (except Motor Vehicle) Merchant Wholesalers"},
{id:423910, value: "Sporting and Recreational Goods and Supplies Merchant Wholesalers"},
{id:423920, value: "Toy and Hobby Goods and Supplies Merchant Wholesalers"},
{id:423930, value: "Recyclable Material Merchant Wholesalers"},
{id:423940  , value: "Jewelry, Watch, Precious Stone, and Precious Metal Merchant Wholesalers"},
{id:423990, value: "Other Miscellaneous Durable Goods Merchant Wholesalers"},
{id:424110, value: "Printing and Writing Paper Merchant Wholesalers"},
{id:424120, value: "Stationery and Office Supplies Merchant Wholesalers"},
{id:424130, value: "Industrial and Personal Service Paper Merchant Wholesalers"},
{id:424210, value: "Drugs and Druggists' Sundries Merchant Wholesalers"},
{id:424310  , value: "Piece Goods, Notions, and Other Dry Goods Merchant Wholesalers"},
{id:424320, value: "Men's and Boys' Clothing and Furnishings Merchant Wholesalers"},
{id:424330  , value: "Women's, Children's, and Infants' Clothing and Accessories Merchant Wholesalers"},
{id:424340, value: "Footwear Merchant Wholesalers"},
{id:424410, value: "General Line Grocery Merchant Wholesalers"},
{id:424420, value: "Packaged Frozen Food Merchant Wholesalers"},
{id:424430, value: "Dairy Product (except Dried or Canned) Merchant Wholesalers"},
{id:424440, value: "Poultry and Poultry Product Merchant Wholesalers"},
{id:424450, value: "Confectionery Merchant Wholesalers"},
{id:424460, value: "Fish and Seafood Merchant Wholesalers"},
{id:424470, value: "Meat and Meat Product Merchant Wholesalers"},
{id:424480, value: "Fresh Fruit and Vegetable Merchant Wholesalers"},
{id:424490, value: "Other Grocery and Related Products Merchant Wholesalers"},
{id:424510, value: "Grain and Field Bean Merchant Wholesalers"},
{id:424520, value: "Livestock Merchant Wholesalers"},
{id:424590, value: "Other Farm Product Raw Material Merchant Wholesalers"},
{id:424610, value: "Plastics Materials and Basic Forms and Shapes Merchant Wholesalers"},
{id:424690, value: "Other Chemical and Allied Products Merchant Wholesalers"},
{id:424710, value: "Petroleum Bulk Stations and Terminals"},
{id:424720, value: "Petroleum and Petroleum Products Merchant Wholesalers (except Bulk Stations and Terminals)"},
{id:424810, value: "Beer and Ale Merchant Wholesalers"},
{id:424820, value: "Wine and Distilled Alcoholic Beverage Merchant Wholesalers"},
{id:424910, value: "Farm Supplies Merchant Wholesalers"},
{id:424920  , value: "Book, Periodical, and Newspaper Merchant Wholesalers"},
{id:424930  , value: "Flower, Nursery Stock, and Florists' Supplies Merchant Wholesalers"},
{id:424940, value: "Tobacco and Tobacco Product Merchant Wholesalers"},
{id:424950  , value: "Paint, Varnish, and Supplies Merchant Wholesalers"},
{id:424990, value: "Other Miscellaneous Nondurable Goods Merchant Wholesalers"},
{id:425110, value: "Business to Business Electronic Markets"},
{id:425120, value: "Wholesale Trade Agents and Brokers"},
{id:441110, value: "New Car Dealers"},
{id:441120, value: "Used Car Dealers"},
{id:441210, value: "Recreational Vehicle Dealers"},
{id:441221, value: "Motorcycle, ATV, and Personal Watercraft Dealers"},
{id:441222, value: "Boat Dealers"},
{id:441229, value: "All Other Motor Vehicle Dealers"},
{id:441310, value: "Automotive Parts and Accessories Stores"},
{id:441320, value: "Tire Dealers"},
{id:442110, value: "Furniture Stores"},
{id:442210, value: "Floor Covering Stores"},
{id:442291, value: "Window Treatment Stores"},
{id:442299, value: "All Other Home Furnishings Stores"},
{id:443111, value: "Household Appliance Stores"},
{id:443112  , value: "Radio, Television, and Other Electronics Stores"},
{id:443120, value: "Computer and Software Stores"},
{id:443130, value: "Camera and Photographic Supplies Stores"},
{id:444110, value: "Home Centers"},
{id:444120, value: "Paint and Wallpaper Stores"},
{id:444130, value: "Hardware Stores"},
{id:444190, value: "Other Building Material Dealers"},
{id:444210, value: "Outdoor Power Equipment Stores"},
{id:444220  , value: "Nursery, Garden Center, and Farm Supply Stores"},
{id:445110, value: "Supermarkets and Other Grocery (except Convenience) Stores"},
{id:445120, value: "Convenience Stores"},
{id:445210, value: "Meat Markets"},
{id:445220, value: "Fish and Seafood Markets"},
{id:445230, value: "Fruit and Vegetable Markets"},
{id:445291, value: "Baked Goods Stores"},
{id:445292, value: "Confectionery and Nut Stores"},
{id:445299, value: "All Other Specialty Food Stores"},
{id:445310  , value: "Beer, Wine, and Liquor Stores"},
{id:446110, value: "Pharmacies and Drug Stores"},
{id:446120  , value: "Cosmetics, Beauty Supplies, and Perfume Stores"},
{id:446130, value: "Optical Goods Stores"},
{id:446191, value: "Food (Health) Supplement Stores"},
{id:446199, value: "All Other Health and Personal Care Stores"},
{id:447110, value: "Gasoline Stations with Convenience Stores"},
{id:447190, value: "Other Gasoline Stations"},
{id:448110, value: "Men's Clothing Stores"},
{id:448120, value: "Women's Clothing Stores"},
{id:448130, value: "Children's and Infants' Clothing Stores"},
{id:448140, value: "Family Clothing Stores"},
{id:448150, value: "Clothing Accessories Stores"},
{id:448190, value: "Other Clothing Stores"},
{id:448210, value: "Shoe Stores"},
{id:448310, value: "Jewelry Stores"},
{id:448320, value: "Luggage and Leather Goods Stores"},
{id:451110, value: "Sporting Goods Stores"},
{id:451120  , value: "Hobby, Toy, and Game Stores"},
{id:451130  , value: "Sewing, Needlework, and Piece Goods Stores"},
{id:451140, value: "Musical Instrument and Supplies Stores"},
{id:451211, value: "Book Stores"},
{id:451212, value: "News Dealers and Newsstands"},
{id:451220  , value: "Prerecorded Tape, Compact Disc, and Record Stores"},
{id:452111, value: "Department Stores (except Discount Department Stores)"},
{id:452112, value: "Discount Department Stores"},
{id:452910, value: "Warehouse Clubs and Supercenters"},
{id:452990, value: "All Other General Merchandise Stores"},
{id:453110, value: "Florists"},
{id:453210, value: "Office Supplies and Stationery Stores"},
{id:453220  , value: "Gift, Novelty, and Souvenir Stores"},
{id:453310, value: "Used Merchandise Stores"},
{id:453910, value: "Pet and Pet Supplies Stores"},
{id:453920, value: "Art Dealers"},
{id:453930, value: "Manufactured (Mobile) Home Dealers"},
{id:453991, value: "Tobacco Stores"},
{id:453998, value: "All Other Miscellaneous Store Retailers (except Tobacco Stores)"},
{id:454111, value: "Electronic Shopping"},
{id:454112, value: "Electronic Auctions"},
{id:454113, value: "Mail-Order Houses"},
{id:454210, value: "Vending Machine Operators"},
{id:454311, value: "Heating Oil Dealers"},
{id:454312, value: "Liquefied Petroleum Gas (Bottled Gas) Dealers"},
{id:454319, value: "Other Fuel Dealers"},
{id:454390, value: "Other Direct Selling Establishments"},
{id:481111, value: "Scheduled Passenger Air Transportation"},
{id:481112, value: "Scheduled Freight Air Transportation"},
{id:481211, value: "Nonscheduled Chartered Passenger Air Transportation"},
{id:481212, value: "Nonscheduled Chartered Freight Air Transportation"},
{id:481219, value: "Other Nonscheduled Air Transportation"},
{id:482111, value: "Line-Haul Railroads"},
{id:482112, value: "Short Line Railroads"},
{id:483111, value: "Deep Sea Freight Transportation"},
{id:483112, value: "Deep Sea Passenger Transportation"},
{id:483113, value: "Coastal and Great Lakes Freight Transportation"},
{id:483114, value: "Coastal and Great Lakes Passenger Transportation"},
{id:483211, value: "Inland Water Freight Transportation"},
{id:483212, value: "Inland Water Passenger Transportation"},
{id:484110  , value: "General Freight Trucking, Local"},
{id:484121  , value: "General Freight Trucking, Long-Distance, Truckload"},
{id:484122  , value: "General Freight Trucking, Long-Distance, Less Than Truckload"},
{id:484210, value: "Used Household and Office Goods Moving"},
{id:484220  , value: "Specialized Freight (except Used Goods) Trucking, Local"},
{id:484230  , value: "Specialized Freight (except Used Goods) Trucking, Long-Distance"},
{id:485111, value: "Mixed Mode Transit Systems"},
{id:485112, value: "Commuter Rail Systems"},
{id:485113, value: "Bus and Other Motor Vehicle Transit Systems"},
{id:485119, value: "Other Urban Transit Systems"},
{id:485210, value: "Interurban and Rural Bus Transportation"},
{id:485310, value: "Taxi Service"},
{id:485320, value: "Limousine Service"},
{id:485410, value: "School and Employee Bus Transportation"},
{id:485510, value: "Charter Bus Industry"},
{id:485991, value: "Special Needs Transportation"},
{id:485999, value: "All Other Transit and Ground Passenger Transportation"},
{id:486110, value: "Pipeline Transportation of Crude Oil"},
{id:486210, value: "Pipeline Transportation of Natural Gas"},
{id:486910, value: "Pipeline Transportation of Refined Petroleum Products"},
{id:486990, value: "All Other Pipeline Transportation"},
{id:487110  , value: "Scenic and Sightseeing Transportation, Land"},
{id:487210  , value: "Scenic and Sightseeing Transportation, Water"},
{id:487990  , value: "Scenic and Sightseeing Transportation, Other"},
{id:488111, value: "Air Traffic Control"},
{id:488119, value: "Other Airport Operations"},
{id:488190, value: "Other Support Activities for Air Transportation"},
{id:488210, value: "Support Activities for Rail Transportation"},
{id:488310, value: "Port and Harbor Operations"},
{id:488320, value: "Marine Cargo Handling"},
{id:488330, value: "Navigational Services to Shipping"},
{id:488390, value: "Other Support Activities for Water Transportation"},
{id:488410, value: "Motor Vehicle Towing"},
{id:488490, value: "Other Support Activities for Road Transportation"},
{id:488510, value: "Freight Transportation Arrangement"},
{id:488991, value: "Packing and Crating"},
{id:488999, value: "All Other Support Activities for Transportation"},
{id:491110, value: "Postal Service"},
{id:492110, value: "Couriers and Express Delivery Services"},
{id:492210, value: "Local Messengers and Local Delivery"},
{id:493110, value: "General Warehousing and Storage"},
{id:493120, value: "Refrigerated Warehousing and Storage"},
{id:493130, value: "Farm Product Warehousing and Storage"},
{id:493190, value: "Other Warehousing and Storage"},
{id:511110, value: "Newspaper Publishers"},
{id:511120, value: "Periodical Publishers"},
{id:511130, value: "Book Publishers"},
{id:511140, value: "Directory and Mailing List Publishers"},
{id:511191, value: "Greeting Card Publishers"},
{id:511199, value: "All Other Publishers"},
{id:511210, value: "Software Publishers"},
{id:512110, value: "Motion Picture and Video Production"},
{id:512120, value: "Motion Picture and Video Distribution"},
{id:512131, value: "Motion Picture Theaters (except Drive-Ins)"},
{id:512132, value: "Drive-In Motion Picture Theaters"},
{id:512191, value: "Teleproduction and Other Postproduction Services"},
{id:512199, value: "Other Motion Picture and Video Industries"},
{id:512210, value: "Record Production"},
{id:512220, value: "Integrated Record Production/Distribution"},
{id:512230, value: "Music Publishers"},
{id:512240, value: "Sound Recording Studios"},
{id:512290, value: "Other Sound Recording Industries"},
{id:515111, value: "Radio Networks"},
{id:515112, value: "Radio Stations"},
{id:515120, value: "Television Broadcasting"},
{id:515210, value: "Cable and Other Subscription Programming"},
{id:517110, value: "Wired Telecommunications Carriers"},
{id:517210, value: "Wireless Telecommunications Carriers (except Satellite)"},
{id:517410, value: "Satellite Telecommunications"},
{id:517911, value: "Telecommunications Resellers"},
{id:517919, value: "All Other Telecommunications"},
{id:518210  , value: "Data Processing, Hosting, and Related Services"},
{id:519110, value: "News Syndicates"},
{id:519120, value: "Libraries and Archives"},
{id:519130, value: "Internet Publishing and Broadcasting and Web Search Portals"},
{id:519190, value: "All Other Information Services"},
{id:521110, value: "Monetary Authorities - Central Bank"},
{id:522110, value: "Commercial Banking"},
{id:522120, value: "Savings Institutions"},
{id:522130, value: "Credit Unions"},
{id:522190, value: "Other Depository Credit Intermediation"},
{id:522210, value: "Credit Card Issuing"},
{id:522220, value: "Sales Financing"},
{id:522291, value: "Consumer Lending"},
{id:522292, value: "Real Estate Credit"},
{id:522293, value: "International Trade Financing"},
{id:522294, value: "Secondary Market Financing"},
{id:522298, value: "All Other Nondepository Credit Intermediation"},
{id:522310, value: "Mortgage and Nonmortgage Loan Brokers"},
{id:522320  , value: "Financial Transactions Processing, Reserve, and Clearinghouse Activities"},
{id:522390, value: "Other Activities Related to Credit Intermediation"},
{id:523110, value: "Investment Banking and Securities Dealing"},
{id:523120, value: "Securities Brokerage"},
{id:523130, value: "Commodity Contracts Dealing"},
{id:523140, value: "Commodity Contracts Brokerage"},
{id:523210, value: "Securities and Commodity Exchanges"},
{id:523910, value: "Miscellaneous Intermediation"},
{id:523920, value: "Portfolio Management"},
{id:523930, value: "Investment Advice"},
{id:523991  , value: "Trust, Fiduciary, and Custody Activities"},
{id:523999, value: "Miscellaneous Financial Investment Activities"},
{id:524113, value: "Direct Life Insurance Carriers"},
{id:524114, value: "Direct Health and Medical Insurance Carriers"},
{id:524126, value: "Direct Property and Casualty Insurance Carriers"},
{id:524127, value: "Direct Title Insurance Carriers"},
{id:524128 , value: "Other Direct Insurance (except Life, Health, and Medical) Carriers"},
{id:524130, value: "Reinsurance Carriers"},
{id:524210, value: "Insurance Agencies and Brokerages"},
{id:524291, value: "Claims Adjusting"},
{id:524292, value: "Third Party Administration of Insurance and Pension Funds"},
{id:524298, value: "All Other Insurance Related Activities"},
{id:525110, value: "Pension Funds"},
{id:525120, value: "Health and Welfare Funds"},
{id:525190, value: "Other Insurance Funds"},
{id:525910, value: "Open-End Investment Funds"},
{id:525920  , value: "Trusts, Estates, and Agency Accounts"},
{id:525990, value: "Other Financial Vehicles"},
{id:531110, value: "Lessors of Residential Buildings and Dwellings"},
{id:531120, value: "Lessors of Nonresidential Buildings (except Miniwarehouses)"},
{id:531130, value: "Lessors of Miniwarehouses and Self-Storage Units"},
{id:531190, value: "Lessors of Other Real Estate Property"},
{id:531210, value: "Offices of Real Estate Agents and Brokers"},
{id:531311, value: "Residential Property Managers"},
{id:531312, value: "Nonresidential Property Managers"},
{id:531320, value: "Offices of Real Estate Appraisers"},
{id:531390, value: "Other Activities Related to Real Estate"},
{id:532111, value: "Passenger Car Rental"},
{id:532112, value: "Passenger Car Leasing"},
{id:532120  , value: "Truck, Utility Trailer, and RV (Recreational Vehicle) Rental and Leasing"},
{id:532210, value: "Consumer Electronics and Appliances Rental"},
{id:532220, value: "Formal Wear and Costume Rental"},
{id:532230, value: "Video Tape and Disc Rental"},
{id:532291, value: "Home Health Equipment Rental"},
{id:532292, value: "Recreational Goods Rental"},
{id:532299, value: "All Other Consumer Goods Rental"},
{id:532310, value: "General Rental Centers"},
{id:532411  , value: "Commercial Air, Rail, and Water Transportation Equipment Rental and Leasing"},
{id:532412  , value: "Construction, Mining, and Forestry Machinery and Equipment Rental and Leasing"},
{id:532420, value: "Office Machinery and Equipment Rental and Leasing"},
{id:532490, value: "Other Commercial and Industrial Machinery and Equipment Rental and Leasing"},
{id:533110, value: "Lessors of Nonfinancial Intangible Assets (except Copyrighted Works)"},
{id:541110, value: "Offices of Lawyers"},
{id:541120, value: "Offices of Notaries"},
{id:541191, value: "Title Abstract and Settlement Offices"},
{id:541199, value: "All Other Legal Services"},
{id:541211, value: "Offices of Certified Public Accountants"},
{id:541213, value: "Tax Preparation Services"},
{id:541214, value: "Payroll Services"},
{id:541219, value: "Other Accounting Services"},
{id:541310, value: "Architectural Services"},
{id:541320, value: "Landscape Architectural Services"},
{id:541330, value: "Engineering Services"},
{id:541340, value: "Drafting Services"},
{id:541350, value: "Building Inspection Services"},
{id:541360, value: "Geophysical Surveying and Mapping Services"},
{id:541370, value: "Surveying and Mapping (except Geophysical) Services"},
{id:541380, value: "Testing Laboratories"},
{id:541410, value: "Interior Design Services"},
{id:541420, value: "Industrial Design Services"},
{id:541430, value: "Graphic Design Services"},
{id:541490, value: "Other Specialized Design Services"},
{id:541511, value: "Custom Computer Programming Services"},
{id:541512, value: "Computer Systems Design Services"},
{id:541513, value: "Computer Facilities Management Services"},
{id:541519, value: "Other Computer Related Services"},
{id:541611, value: "Administrative Management and General Management Consulting Services"},
{id:541612, value: "Human Resources Consulting Services"},
{id:541613, value: "Marketing Consulting Services"},
{id:541614  , value: "Process, Physical Distribution, and Logistics Consulting Services"},
{id:541618, value: "Other Management Consulting Services"},
{id:541620, value: "Environmental Consulting Services"},
{id:541690, value: "Other Scientific and Technical Consulting Services"},
{id:541711 , value: "Research and Development in Biotechnology"},
{id:541712, value: "Reseach and Development in the Physical, Engineering, and Life Sciences (except Biotechnology)"},
{id:541720, value: "Research and Development in the Social Sciences and Humanities"},
{id:541810, value: "Advertising Agencies"},
{id:541820, value: "Public Relations Agencies"},
{id:541830, value: "Media Buying Agencies"},
{id:541840, value: "Media Representatives"},
{id:541850, value: "Display Advertising"},
{id:541860, value: "Direct Mail Advertising"},
{id:541870, value: "Advertising Material Distribution Services"},
{id:541890, value: "Other Services Related to Advertising"},
{id:541910, value: "Marketing Research and Public Opinion Polling"},
{id:541921  , value: "Photography Studios, Portrait"},
{id:541922, value: "Commercial Photography"},
{id:541930, value: "Translation and Interpretation Services"},
{id:541940, value: "Veterinary Services"},
{id:541990  , value: "All Other Professional, Scientific, and Technical Services"},
{id:551111, value: "Offices of Bank Holding Companies"},
{id:551112, value: "Offices of Other Holding Companies"},
{id:551114  , value: "Corporate, Subsidiary, and Regional Managing Offices"},
{id:561110, value: "Office Administrative Services"},
{id:561210, value: "Facilities Support Services"},
{id:561311, value: "Employment Placement Agencies"},
{id:561312, value: "Executive Search Services"},
{id:561320, value: "Temporary Help Services"},
{id:561330, value: "Professional Employer Organizations"},
{id:561410, value: "Document Preparation Services"},
{id:561421, value: "Telephone Answering Services"},
{id:561422, value: "Telemarketing Bureaus and Other Contact Centers"},
{id:561431, value: "Private Mail Centers"},
{id:561439, value: "Other Business Service Centers (including Copy Shops)"},
{id:561440, value: "Collection Agencies"},
{id:561450, value: "Credit Bureaus"},
{id:561491, value: "Repossession Services"},
{id:561492, value: "Court Reporting and Stenotype Services"},
{id:561499, value: "All Other Business Support Services"},
{id:561510, value: "Travel Agencies"},
{id:561520, value: "Tour Operators"},
{id:561591, value: "Convention and Visitors Bureaus"},
{id:561599, value: "All Other Travel Arrangement and Reservation Services"},
{id:561611, value: "Investigation Services"},
{id:561612, value: "Security Guards and Patrol Services"},
{id:561613, value: "Armored Car Services"},
{id:561621, value: "Security Systems Services (except Locksmiths)"},
{id:561622, value: "Locksmiths"},
{id:561710, value: "Exterminating and Pest Control Services"},
{id:561720, value: "Janitorial Services"},
{id:561730, value: "Landscaping Services"},
{id:561740, value: "Carpet and Upholstery Cleaning Services"},
{id:561790, value: "Other Services to Buildings and Dwellings"},
{id:561910, value: "Packaging and Labeling Services"},
{id:561920, value: "Convention and Trade Show Organizers"},
{id:561990, value: "All Other Support Services"},
{id:562111, value: "Solid Waste Collection"},
{id:562112, value: "Hazardous Waste Collection"},
{id:562119, value: "Other Waste Collection"},
{id:562211, value: "Hazardous Waste Treatment and Disposal"},
{id:562212, value: "Solid Waste Landfill"},
{id:562213, value: "Solid Waste Combustors and Incinerators"},
{id:562219, value: "Other Nonhazardous Waste Treatment and Disposal"},
{id:562910, value: "Remediation Services"},
{id:562920, value: "Materials Recovery Facilities"},
{id:562991, value: "Septic Tank and Related Services"},
{id:562998, value: "All Other Miscellaneous Waste Management Services"},
{id:611110, value: "Elementary and Secondary Schools"},
{id:611210, value: "Junior Colleges"},
{id:611310  , value: "Colleges, Universities, and Professional Schools"},
{id:611410, value: "Business and Secretarial Schools"},
{id:611420, value: "Computer Training"},
{id:611430, value: "Professional and Management Development Training"},
{id:611511, value: "Cosmetology and Barber Schools"},
{id:611512, value: "Flight Training"},
{id:611513, value: "Apprenticeship Training"},
{id:611519, value: "Other Technical and Trade Schools"},
{id:611610, value: "Fine Arts Schools"},
{id:611620, value: "Sports and Recreation Instruction"},
{id:611630, value: "Language Schools"},
{id:611691, value: "Exam Preparation and Tutoring"},
{id:611692, value: "Automobile Driving Schools"},
{id:611699, value: "All Other Miscellaneous Schools and Instruction"},
{id:611710, value: "Educational Support Services"},
{id:621111, value: "Offices of Physicians (except Mental Health Specialists)"},
{id:621112  , value: "Offices of Physicians, Mental Health Specialists"},
{id:621210, value: "Offices of Dentists"},
{id:621310, value: "Offices of Chiropractors"},
{id:621320, value: "Offices of Optometrists"},
{id:621330, value: "Offices of Mental Health Practitioners (except Physicians)"},
{id:621340  , value: "Offices of Physical, Occupational and Speech Therapists, and Audiologists"},
{id:621391, value: "Offices of Podiatrists"},
{id:621399, value: "Offices of All Other Miscellaneous Health Practitioners"},
{id:621410, value: "Family Planning Centers"},
{id:621420, value: "Outpatient Mental Health and Substance Abuse Centers"},
{id:621491, value: "HMO Medical Centers"},
{id:621492, value: "Kidney Dialysis Centers"},
{id:621493, value: "Freestanding Ambulatory Surgical and Emergency Centers"},
{id:621498, value: "All Other Outpatient Care Centers"},
{id:621511, value: "Medical Laboratories"},
{id:621512, value: "Diagnostic Imaging Centers"},
{id:621610, value: "Home Health Care Services"},
{id:621910, value: "Ambulance Services"},
{id:621991, value: "Blood and Organ Banks"},
{id:621999, value: "All Other Miscellaneous Ambulatory Health Care Services"},
{id:622110, value: "General Medical and Surgical Hospitals"},
{id:622210, value: "Psychiatric and Substance Abuse Hospitals"},
{id:622310, value: "Specialty (except Psychiatric and Substance Abuse) Hospitals"},
{id:623110, value: "Nursing Care Facilities"},
{id:623210, value: "Residential Mental Retardation Facilities"},
{id:623220, value: "Residential Mental Health and Substance Abuse Facilities"},
{id:623311, value: "Continuing Care Retirement Communities"},
{id:623312, value: "Homes for the Elderly"},
{id:623990, value: "Other Residential Care Facilities"},
{id:624110, value: "Child and Youth Services"},
{id:624120, value: "Services for the Elderly and Persons with Disabilities"},
{id:624190, value: "Other Individual and Family Services"},
{id:624210, value: "Community Food Services"},
{id:624221, value: "Temporary Shelters"},
{id:624229, value: "Other Community Housing Services"},
{id:624230, value: "Emergency and Other Relief Services"},
{id:624310, value: "Vocational Rehabilitation Services"},
{id:624410, value: "Child Day Care Services"},
{id:711110, value: "Theater Companies and Dinner Theaters"},
{id:711120, value: "Dance Companies"},
{id:711130, value: "Musical Groups and Artists"},
{id:711190, value: "Other Performing Arts Companies"},
{id:711211, value: "Sports Teams and Clubs"},
{id:711212, value: "Racetracks"},
{id:711219, value: "Other Spectator Sports"},
{id:711310  , value: "Promoters of Performing Arts, Sports, and Similar Events with Facilities"},
{id:711320  , value: "Promoters of Performing Arts, Sports, and Similar Events without Facilities"},
{id:711410  , value: "Agents and Managers for Artists, Athletes, Entertainers, and Other Public Figures"},
{id:711510 , value: "Independent Artists, Writers, and Performers"},
{id:712110, value: "Museums"},
{id:712120, value: "Historical Sites"},
{id:712130, value: "Zoos and Botanical Gardens"},
{id:712190, value: "Nature Parks and Other Similar Institutions"},
{id:713110, value: "Amusement and Theme Parks"},
{id:713120, value: "Amusement Arcades"},
{id:713210, value: "Casinos (except Casino Hotels)"},
{id:713290, value: "Other Gambling Industries"},
{id:713910, value: "Golf Courses and Country Clubs"},
{id:713920, value: "Skiing Facilities"},
{id:713930, value: "Marinas"},
{id:713940, value: "Fitness and Recreational Sports Centers"},
{id:713950, value: "Bowling Centers"},
{id:713990, value: "All Other Amusement and Recreation Industries"},
{id:721110, value: "Hotels (except Casino Hotels) and Motels"},
{id:721120, value: "Casino Hotels"},
{id:721191, value: "Bed-and-Breakfast Inns"},
{id:721199, value: "All Other Traveler Accommodation"},
{id:721211, value: "RV (Recreational Vehicle) Parks and Campgrounds"},
{id:721214, value: "Recreational and Vacation Camps (except Campgrounds)"},
{id:721310, value: "Rooming and Boarding Houses"},
{id:722110, value: "Full-Service Restaurants"},
{id:722211, value: "Limited-Service Restaurants"},
{id:722212, value: "Cafeterias, Grill Buffets, and Buffets"},
{id:722213, value: "Snack and Nonalcoholic Beverage Bars"},
{id:722310, value: "Food Service Contractors"},
{id:722320, value: "Caterers"},
{id:722330, value: "Mobile Food Services"},
{id:722410, value: "Drinking Places (Alcoholic Beverages)"},
{id:811111, value: "General Automotive Repair"},
{id:811112, value: "Automotive Exhaust System Repair"},
{id:811113, value: "Automotive Transmission Repair"},
{id:811118, value: "Other Automotive Mechanical and Electrical Repair and Maintenance"},
{id:811121  , value: "Automotive Body, Paint, and Interior Repair and Maintenance"},
{id:811122, value: "Automotive Glass Replacement Shops"},
{id:811191, value: "Automotive Oil Change and Lubrication Shops"},
{id:811192, value: "Car Washes"},
{id:811198, value: "All Other Automotive Repair and Maintenance"},
{id:811211, value: "Consumer Electronics Repair and Maintenance"},
{id:811212, value: "Computer and Office Machine Repair and Maintenance"},
{id:811213, value: "Communication Equipment Repair and Maintenance"},
{id:811219, value: "Other Electronic and Precision Equipment Repair and Maintenance"},
{id:811310, value: "Commercial and Industrial Machinery and Equipment (except Automotive and Electronic) Repair and Maintenance"},
{id:811411, value: "Home and Garden Equipment Repair and Maintenance"},
{id:811412, value: "Appliance Repair and Maintenance"},
{id:811420, value: "Reupholstery and Furniture Repair"},
{id:811430, value: "Footwear and Leather Goods Repair"},
{id:811490, value: "Other Personal and Household Goods Repair and Maintenance"},
{id:812111, value: "Barber Shops"},
{id:812112, value: "Beauty Salons"},
{id:812113, value: "Nail Salons"},
{id:812191, value: "Diet and Weight Reducing Centers"},
{id:812199, value: "Other Personal Care Services"},
{id:812210, value: "Funeral Homes and Funeral Services"},
{id:812220, value: "Cemeteries and Crematories"},
{id:812310, value: "Coin-Operated Laundries and Drycleaners"},
{id:812320, value: "Drycleaning and Laundry Services (except Coin-Operated)"},
{id:812331, value: "Linen Supply"},
{id:812332, value: "Industrial Launderers"},
{id:812910, value: "Pet Care (except Veterinary) Services"},
{id:812921, value: "Photofinishing Laboratories (except One-Hour)"},
{id:812922, value: "One-Hour Photofinishing"},
{id:812930, value: "Parking Lots and Garages"},
{id:812990, value: "All Other Personal Services"},
{id:813110, value: "Religious Organizations"},
{id:813211, value: "Grantmaking Foundations"},
{id:813212, value: "Voluntary Health Organizations"},
{id:813219, value: "Other Grantmaking and Giving Services"},
{id:813311, value: "Human Rights Organizations"},
{id:813312  , value: "Environment, Conservation and Wildlife Organizations"},
{id:813319, value: "Other Social Advocacy Organizations"},
{id:813410, value: "Civic and Social Organizations"},
{id:813910, value: "Business Associations"},
{id:813920, value: "Professional Organizations"},
{id:813930, value: "Labor Unions and Similar Labor Organizations"},
{id:813940, value: "Political Organizations"},
{id:813990  , value: "Other Similar Organizations (except Business, Professional, Labor, and Political Organizations)"},
{id:814110, value: "Private Households"},
{id:921110, value: "Executive Offices"},
{id:921120, value: "Legislative Bodies"},
{id:921130, value: "Public Finance Activities"},
{id:921140  , value: "Executive and Legislative Offices, Combined"},
{id:921150, value: "American Indian and Alaska Native Tribal Governments"},
{id:921190, value: "Other General Government Support"},
{id:922110, value: "Courts"},
{id:922120, value: "Police Protection"},
{id:922130, value: "Legal Counsel and Prosecution"},
{id:922140, value: "Correctional Institutions"},
{id:922150, value: "Parole Offices and Probation Offices"},
{id:922160, value: "Fire Protection"},
{id:922190  , value: "Other Justice, Public Order, and Safety Activities"},
{id:923110, value: "Administration of Education Programs"},
{id:923120, value: "Administration of Public Health Programs"},
{id:923130  , value: "Administration of Human Resource Programs (except Education, Public Health, and Veterans' Affairs Programs)"},
{id:923140, value: "Administration of Veterans' Affairs"},
{id:924110, value: "Administration of Air and Water Resource and Solid Waste Management Programs"},
{id:924120, value: "Administration of Conservation Programs"},
{id:925110, value: "Administration of Housing Programs"},
{id:925120, value: "Administration of Urban Planning and Community and Rural Development"},
{id:926110, value: "Administration of General Economic Programs"},
{id:926120, value: "Regulation and Administration of Transportation Programs"},
{id:926130  , value: "Regulation and Administration of Communications, Electric, Gas, and Other Utilities"},
{id:926140, value: "Regulation of Agricultural Marketing and Commodities"},
{id:926150  , value: "Regulation, Licensing, and Inspection of Miscellaneous Commercial Sectors"},
{id:927110, value: "Space Research and Technology"},
{id:928110, value: "National Security"},
{id:928120, value: "International Affairs"},
{id:990000, value: "Residential"}
    ];

    var foundWords = Search(
        word,
        phraseList,
        .1);

    

